commands = [
    ('show', "Display information on a node"),
    ('remove', "Remove a node (stopping it if necessary and deleting all its data)"),
    ('showlog', "Show the log of node name (runs your $PAGER on its system.log)"),
    ('setlog', "Set node name log level (INFO, DEBUG, ...) with/without Java class - require a node restart"),
    ('start', "Start a node"),
    ('stop', "Stop a node"),
    ('ring', "Print ring (connecting to node name)"),
    ('flush', "Flush node name"),
    ('compact', "Compact node name"),
    ('drain', "Drain node name"),
    ('cleanup', "Run cleanup on node name"),
    ('repair', "Run repair on node name"),
    ('scrub', "Scrub files"),
    ('verify', "Verify files"),
    ('shuffle', "Run shuffle on a node"),
    ('sstablesplit', "Run sstablesplit on the sstables of this node"),
    ('getsstables', "Run getsstables to get absolute path of sstables in this node"),
    ('decommission', "Run decommission on node name"),
    ('json', "Call sstable2json/sstabledump on the sstables of this node"),
    ('updateconf', "Update the cassandra config files for this node (useful when updating cassandra)"),
    ('updatelog4j', "Update the Cassandra log4j-server.properties configuration file under given node"),
    ('stress', "Run stress on a node"),
    ('cli', "Launch a cassandra cli connected to this node"),
    ('cqlsh', "Launch a cqlsh session connected to this node"),
    ('scrub', "Scrub files"),
    ('verify', "Verify files"),
    ('status', "Print status (connecting to node name)"),
    ('setdir', "Set the cassandra directory to use for the node"),
    ('bulkload', "Bulkload files into the cluster by connecting to this node"),
    ('version', "Get the cassandra version of node"),
    ('nodetool', "Run nodetool (connecting to node name)"),
    ('dsetool', "Run dsetool (connecting to node name)"),
    ('setworkload', "Sets the workloads for a DSE node"),
    ('dse', "Launch a dse client application connected to this node"),
    ('hadoop', "Launch a hadoop session connected to this node"),
    ('hive', "Launch a hive session connected to this node"),
    ('pig', "Launch a pig session connected to this node"),
    ('sqoop', "Launch a sqoop session connected to this node"),
    ('spark', "Launch a spark session connected to this node"),
    ('pause', "Send a SIGSTOP to this node"),
    ('resume', "Send a SIGCONT to this node"),
    ('jconsole', "Opens jconsole client and connect to running node"),
    ('versionfrombuild', "Print the node's version as grepped from build.xml. Can be used when the node isn't running."),
    ('byteman', "Invoke byteman-submit"),
]
